name = "macro"
compatibility_date = "2026-02-27"
workers_dev = true
main = "worker.js"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true
not_found_handling = "single-page-application"
